cloudinary_cloud_name: "haile"
cloudinary_api_key: "146464948491269"
cloudinary_api_secret: "DzLWoUnEyCi5E8DwSkp33ZbBsS0"
twitter_app_id: "K7nZSFpuK5NgHlcxFg3UTqdcv"
twitter_app_secret: "3jldKOppO6eNX846zPDfBssvbxzdMB14S2n6OggICUuc62yEdP"
